medium_clone/blog/urls.py
"""
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
"""
from django.urls import path

from .views import create_blog_post_view,tag_view,category_view


app_name = "blog"

urlpatterns = [
    path('create/',create_blog_post_view,name='create_blog_post_view'),
    path('tag/<slug:tag_slug>/',tag_view,name='tag_view'),
    path('category/<slug:category_slug>/',category_view,name='category_view'),
]

medium_clone/config/urls.py
from django.contrib import admin
from django.urls import path,include

from page.views import home_view

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", home_view, name="home_view"),

    #USER
    path('user/', include('user_profile.urls',namespace="user")),

    #BLOG
    path('blog/', include('blog.urls',namespace="blog")),

    #READ
    path('read/', include('read.urls',namespace="read")),
    
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medium_clone/user_profile/urls.py
"""
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
"""
from django.urls import path

from .views import login_view,register_view,logout_view



app_name = "user_profile"

urlpatterns = [
    path("login/", login_view, name="login_view"),
    path("logout/", logout_view, name="logout_view"),
    path("register/", register_view, name="register_view"),
]

medium_clone/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="tr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MD Clone</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>
    {% include "core/messages.html" %}
    <!-- NAVBAR -->
    {% include "core/navbar.html" %}
    <!-- NAVBAR END -->
    <!-- HERO -->
    {% block content %}
    
    {% endblock %}
    
    

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

medium_clone/templates/core/base_without_navbar.html
{% load static %}
<!doctype html>
<html lang="tr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MD Clone</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>
    {% include "core/messages.html" %}
    {% block content %}{% endblock %}
    
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

medium_clone/templates/core/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

medium_clone/templates/core/navbar.html
<nav class="navbar navbar-expand-lg bg-warning border-bottom border-dark">
    <div class="container py-2">
        <a class="navbar-brand" href="/">MD Clone</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:create_blog_post_view' %}">Add Blog</a>
                </li>
                {% if not request.user.is_authenticated %}
                <a class="nav-link" href="{% url 'user_profile:login_view' %}">Login</a>
                <a class="nav-link" href="{% url 'user_profile:register_view' %}">Register</a>
                {% else %}
                <a class="nav-link" href="/admin">Admin</a>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Kategoriler
                    </a>
                    <ul class="dropdown-menu">
                        {% for category in global_categories %}
                        <li><a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category }}</a></li>
                        {% endfor %}
                    </ul>
                  </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      {{ request.user.username }}
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{{ request.user.profile.get_absolute_url }}">My All Posts</a></li>
                    </ul>
                  </li>
  
                <a class="nav-link btn btn-dark text-light px-3 rounded-pill ms-3" href="{% url 'user_profile:logout_view' %}">Logout</a>
                {% endif %}
                </ul>


            <div class="navbar-nav ms-auto">
                
                
                
            </div>
        </div>
    </div>
</nav>